[package]
name = "scamble"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[workspace]
members = ["tester", "tcp_effects", "cassette_player"]

[dependencies]
hound = "3.5.1"

[build-dependencies]
bindgen = "0.71.1"

[features]
fmod_bindings = []