[package]
name = "scamble"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[workspace]
members = ["tester"]

[dependencies]
rand = "0.9.0"
paste = "1.0.15"
circular-buffer = "1.1.0"
realfft = "3.4.0"

[build-dependencies]
bindgen = "0.71.1"

[features]
fmod_bindings = []