[package]
name = "scamble"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0"
paste = "1.0.15"

[build-dependencies]
bindgen = "0.71.1"