[package]
name = "tester"
version = "0.1.0"
edition = "2024"

[dependencies]
scamble = { path = "..", features = ["fmod_bindings"] }
tcp_effects = { path = "../tcp_effects" }
vizia = { git = "https://github.com/vizia/vizia" }
rand = "0.9.0"