name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --lib --verbose --release
    #- name: Run tests
    #  run: cargo test --verbose
    - name: Upload Plugin
      uses: actions/upload-artifact@v4.6.1
      with:
        name: plugin-${{ matrix.os }}
        path: |
          target/release/scamble.dll
          target/release/libscamble.so
          target/release/libscamble.dylib
