name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --lib --verbose
    #- name: Run tests
    #  run: cargo test --verbose
    - name: Upload Plugin
      uses: actions/upload-artifact@v4.6.1
      with:
        name: plugin
        path: |
          target/debug/scamble.dll
          target/debug/libscamble.so
          target/debug/libscamble.dylib
