name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build Cassette Player
      run: cargo build --lib -p cassette_player --verbose --release
    - name: Build TCP Effects
      run: cargo build --lib -p tcp_effects --verbose --release
    - name: Upload Plugin
      uses: actions/upload-artifact@v4.6.1
      with:
        name: plugin-${{ matrix.os }}
        path: |
          target/release/cassette_player.dll
          target/release/libcassette_player.so
          target/release/libcassette_player.dylib
          target/release/tcp_effects.dll
          target/release/libtcp_effects.so
          target/release/libtcp_effects.dylib
